### ISSUE TITLE
Doesn't work (it was me)

### ISSUE THREAD

**Issue by OlsonBolson-dev** [SrS2225a/BetterDiscord#10]
Hey, there are issues: you can click 'add' button and there is a tag, but it disappears when you close profile, also you can't name it and you can't delete a tag

**Comment by SrS2225a** [comment]
Hi there,

Tags only save as type in them, not necessarily when you create them, because otherwise you would be saving nothing. It would be odd to save a tag that does not exist. As for why you can't name them is you properly don't have the text input focused, make sure it is, and if it is not click in the blank space to focus the text input. And also, the reason probably why you can't delete the tag is because the "delete" is known to be a bit finicky, try clicking on it a few times. I tried to get this corrected as best I could, but it is not perfect.

**Comment by OlsonBolson-dev** [comment]
Alright, one issue left, tags don't always save even if are named

**Comment by SrS2225a** [comment]
How so? I tried to reproduce your issue, by adding, removing, and quickly opening the user profile page multiple times and their tags would always show correctly. Do you happen to have the new profile skins feature by any chance? UserTags currently does not work with the new feature, but it will be once it rolls out to everyone. If not, can you give me the steps you did to reproduce?

**Comment by OlsonBolson-dev** [comment]
Weird thing, I've tried to reproduce it, but it worked, so bugs now :D
