### ISSUE TITLE
[Suggestion] (UserTags) Add tags and sort them in settings

### ISSUE THREAD

**Issue by OlsonBolson-dev** [SrS2225a/BetterDiscord#12]
**I came up with something really good: an option to add tags in plugin settings (like roles in server settings).**
You go to the plugin settings and add tags. It'd be cool if there were a color option, but it's not very important.

EDIT:
**I love when everything is organized, so I came up with another idea to make it happen in [UserTags](https://github.com/SrS2225a/BetterDiscord/tree/master/plugins/UserTags).**
So, in the plugin settings, you can sort the tags you added, then every user will have the same order of tags.

**Comment by SrS2225a** [comment]
Interesting idea. I will put this into a "maybe" category

**Comment by OlsonBolson-dev** [comment]
Alright, I hope you make some of this work 🤞

**Comment by SrS2225a** [comment]
Thank you for your suggestion, 

I have done some more thinking and wanted to come around on some of your ideas, and will add just the organization one (I actually planned on adding that feature at some point later one).

Your two other ones sound good in theory, but to me they are not really all that practical. As the plugin settings are more meant for changing a plugins configuration and not the content of said plugin, plus it makes more since to have tags under your profile.

**Comment by SrS2225a** [comment]
Hi there, just responding back to this issue to let you know that your feature request for tag organization has been added! You should see a update soon, but may take a few days depending on when the update request is approved.
