### ISSUE TITLE
FactOfTheDay uses mobile version links to Wikipedia

### ISSUE THREAD

**Issue by Kieubasiarz** [SrS2225a/BetterDiscord#14]
Links are always `en.m.wikipedia.org` not `en.wikipedia.org`, this leads to the mobile version of the website. Is it intentional?
Facts are pulled from your database so we can't change it here.

**Comment by SrS2225a** [comment]
Hello,

Yes. Facts are indeed pulled from my own database. The mobile version of links were sort of intentional as it was just "good enough". I been planning on changing it to the desktop version for some time now, but never gotten around to it as it has been more on the low priority of things. The reason for this is because when I scraped the data, wikipedia somehow thought I was on some kind of mobile device.

Thanks for bringing this to my attention

**Comment by SrS2225a** [comment]
Your suggestion for the links have been fixed! :+1:
