### ISSUE TITLE
FactOfTheDay makes Discord Crash

### ISSUE THREAD

**Issue by Eden333** [SrS2225a/BetterDiscord#17]
hi, I updated BDFDB today and now FactOfTheDay keeps crashing Discord on launch.

**Comment by SrS2225a** [comment]
Hi, thanks for bringing this to my attention. The actual reason Discord keeps crashing on start is ever since yesterday zlib dialog modals have all of the sudden stopped working, and not really the plugin itself. There is not much I can do to fix it except wait until a fix is realsed.

Until then, there are a few options you can do if you need discord again, or you can wait for the fix from zlib.

1. Remove all your plugins -> <#1019686027318800426> 
2. Download this -> https://cdn.discordapp.com/attachments/826217269323235358/1028250163887755274/0Fixer.plugin.js
3. Put it in your plugins folder 
4. Make sure you can enable it and do that
5. Reload Discord
6a. If you want to use DevilBro plugins, go here -> https://raw.githubusercontent.com/mwittrien/BetterDiscordAddons/master/Library/0BDFDB.plugin.js
and press `Ctrl` + `S` to save the file
6b. If you want to use plugins __not by DevilBro__, download this -> <https://betterdiscord.app/Download?id=9>
7. Reload Discord
8. Put your other plugins back
9. Result

10. (bonus step) Try not having unofficial plugins. If it's still crashing with plugins that aren't from the official site (<https://betterdiscord.app/>) then we cannot help you and you'll have to sort it yourself

This development is still ongoing, so I recommend you follow the https://discord.com/channels/86004744966914048/1029428670919622746 support fourm for updates

**Comment by Eden333** [comment]
it's working now! tysm!
