### ISSUE TITLE
A couple facts are straight up false

### ISSUE THREAD

**Issue by TiagoferMC** [SrS2225a/BetterDiscord#21]
So far I've seen two facts that are just flat out incorrect. One claimed that Leonardo DaVinci invented scissors when they a simple search reveals they have been around since at least roman times.

Another one, today's fact, says that "The only nation whose name begins with an "A", but doesn`t end in an "A" is Afghanistan." which is just wrong because Azerbaijan also exists.

Those are the ones I've caught but there's probably more.

**Comment by SrS2225a** [comment]
Hello, when I created my api for the plugin I expected that couple of facts would at least be a bit wrong, this is because the datasource I used for the api were all from wikipedia. And while wikpedia is great as a wiki, it is also known to be at rare occasions be a bit wrong with its facts. It's not perfect I know, but even then, it is still pretty accurate, alot better than the old api I was using before creating my own
