### ISSUE TITLE
ReplaceTimestamps only getting Invalid time format

### ISSUE THREAD

**Issue by itsKline** [SrS2225a/BetterDiscord#22]
I have tried every single combination of prefixes and times and I can't seem to get anything other than "Invalid time format". I tried using your default regex to wrap the text in as well as replacing it and using my own, both still gave the invalid status. I don't know if it is me doing something wrong or if it is a bug but I even tried to use the examples you have in your readme.
![image](https://user-images.githubusercontent.com/104710207/211199030-5143dce5-d914-4526-8391-426f69e7f099.png)

**Comment by SrS2225a** [comment]
Hello,

I have known about this issue for a while now. It is not you, it happened when discord rewrote all of there internals breaking this plugin (and others). Because of this I decided to take a break from plugin development for a while, and only came back a few days ago. Anyways, this will not be fixed and no longer supported since there is already a plugin that does the same before I created this one, I just never realized that it already created. It does not make any since to have multiple plugins that do the same thing, espically since I dont feel like fixing it. You can find the older working plugin at https://betterdiscord.app/plugin/ReplaceTimestamps
