### ISSUE TITLE
Celery does NOT have negative calories

### ISSUE THREAD

**Issue by Zzeyy** [SrS2225a/BetterDiscord#4]
Celery does not contain anything that would cause our body to need to burn calories instead of gaining them.
It has around 16 calories per 100 grams. It IS great for losing weight, it is NOT burning calories.

**Comment by Zzeyy** [comment]
PS: This is not meant to sound arrogant or rude. :) Have a good day.

**Comment by Zzeyy** [comment]
![image](https://user-images.githubusercontent.com/97387354/173512841-e9d0c530-5c14-417d-9a84-0c83c672ff70.png)

**Comment by SrS2225a** [comment]
You have a good day as well. This was explained why this happens in a earlier created issue. https://github.com/SrS2225a/BetterDiscord/issues/2. I think what they mean is that it takes more energy to disgust it as you said. Though recently, I do have the idea of using my own api instead of relying on someone elses. https://github.com/SrS2225a/BetterDiscord/discussions/5
