### ISSUE TITLE
[Suggestion] Only show fact once a day

### ISSUE THREAD

**Issue by keatit71** [SrS2225a/BetterDiscord#6]
I open discord multiple times a day and it would be nice to only have the fact of the day show up once a day not every time i open discord.

**Comment by SrS2225a** [comment]
Hello, sorry for not getting back to you sooner. I have been busy working on some other projects so I did not have the time to check my github.

Anyways, that is a good idea. I just choose not to bother because I normally just have my discord open all day, so it does not normally affect me. But I can see why others may want this. I plan on adding this once I am ready to switch the plugin over to my own api as I am still developing it as the current one I am using kind of sucks.

**Comment by SrS2225a** [comment]
your suggestion has been added :)
